# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tav/Git/Leonidas

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tav/Git/Leonidas

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tav/Git/Leonidas/CMakeFiles /home/tav/Git/Leonidas/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tav/Git/Leonidas/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FRC_UserProgram.out

# Build rule for target.
FRC_UserProgram.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FRC_UserProgram.out
.PHONY : FRC_UserProgram.out

# fast build rule for target.
FRC_UserProgram.out/fast:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/build
.PHONY : FRC_UserProgram.out/fast

#=============================================================================
# Target rules for targets named SFMLNetwork

# Build rule for target.
SFMLNetwork: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SFMLNetwork
.PHONY : SFMLNetwork

# fast build rule for target.
SFMLNetwork/fast:
	$(MAKE) -f SFMLNetwork/CMakeFiles/SFMLNetwork.dir/build.make SFMLNetwork/CMakeFiles/SFMLNetwork.dir/build
.PHONY : SFMLNetwork/fast

#=============================================================================
# Target rules for targets named SFMLSystem

# Build rule for target.
SFMLSystem: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SFMLSystem
.PHONY : SFMLSystem

# fast build rule for target.
SFMLSystem/fast:
	$(MAKE) -f SFMLSystem/CMakeFiles/SFMLSystem.dir/build.make SFMLSystem/CMakeFiles/SFMLSystem.dir/build
.PHONY : SFMLSystem/fast

AutonomousModes/Autonomous.obj: AutonomousModes/Autonomous.cpp.obj
.PHONY : AutonomousModes/Autonomous.obj

# target to build an object file
AutonomousModes/Autonomous.cpp.obj:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/AutonomousModes/Autonomous.cpp.obj
.PHONY : AutonomousModes/Autonomous.cpp.obj

AutonomousModes/Autonomous.i: AutonomousModes/Autonomous.cpp.i
.PHONY : AutonomousModes/Autonomous.i

# target to preprocess a source file
AutonomousModes/Autonomous.cpp.i:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/AutonomousModes/Autonomous.cpp.i
.PHONY : AutonomousModes/Autonomous.cpp.i

AutonomousModes/Autonomous.s: AutonomousModes/Autonomous.cpp.s
.PHONY : AutonomousModes/Autonomous.s

# target to generate assembly for a file
AutonomousModes/Autonomous.cpp.s:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/AutonomousModes/Autonomous.cpp.s
.PHONY : AutonomousModes/Autonomous.cpp.s

ButtonTracker.obj: ButtonTracker.cpp.obj
.PHONY : ButtonTracker.obj

# target to build an object file
ButtonTracker.cpp.obj:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/ButtonTracker.cpp.obj
.PHONY : ButtonTracker.cpp.obj

ButtonTracker.i: ButtonTracker.cpp.i
.PHONY : ButtonTracker.i

# target to preprocess a source file
ButtonTracker.cpp.i:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/ButtonTracker.cpp.i
.PHONY : ButtonTracker.cpp.i

ButtonTracker.s: ButtonTracker.cpp.s
.PHONY : ButtonTracker.s

# target to generate assembly for a file
ButtonTracker.cpp.s:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/ButtonTracker.cpp.s
.PHONY : ButtonTracker.cpp.s

Disabled.obj: Disabled.cpp.obj
.PHONY : Disabled.obj

# target to build an object file
Disabled.cpp.obj:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/Disabled.cpp.obj
.PHONY : Disabled.cpp.obj

Disabled.i: Disabled.cpp.i
.PHONY : Disabled.i

# target to preprocess a source file
Disabled.cpp.i:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/Disabled.cpp.i
.PHONY : Disabled.cpp.i

Disabled.s: Disabled.cpp.s
.PHONY : Disabled.s

# target to generate assembly for a file
Disabled.cpp.s:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/Disabled.cpp.s
.PHONY : Disabled.cpp.s

DriverStationDisplay.obj: DriverStationDisplay.cpp.obj
.PHONY : DriverStationDisplay.obj

# target to build an object file
DriverStationDisplay.cpp.obj:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/DriverStationDisplay.cpp.obj
.PHONY : DriverStationDisplay.cpp.obj

DriverStationDisplay.i: DriverStationDisplay.cpp.i
.PHONY : DriverStationDisplay.i

# target to preprocess a source file
DriverStationDisplay.cpp.i:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/DriverStationDisplay.cpp.i
.PHONY : DriverStationDisplay.cpp.i

DriverStationDisplay.s: DriverStationDisplay.cpp.s
.PHONY : DriverStationDisplay.s

# target to generate assembly for a file
DriverStationDisplay.cpp.s:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/DriverStationDisplay.cpp.s
.PHONY : DriverStationDisplay.cpp.s

Kinect/DriveKinect.obj: Kinect/DriveKinect.cpp.obj
.PHONY : Kinect/DriveKinect.obj

# target to build an object file
Kinect/DriveKinect.cpp.obj:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/Kinect/DriveKinect.cpp.obj
.PHONY : Kinect/DriveKinect.cpp.obj

Kinect/DriveKinect.i: Kinect/DriveKinect.cpp.i
.PHONY : Kinect/DriveKinect.i

# target to preprocess a source file
Kinect/DriveKinect.cpp.i:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/Kinect/DriveKinect.cpp.i
.PHONY : Kinect/DriveKinect.cpp.i

Kinect/DriveKinect.s: Kinect/DriveKinect.cpp.s
.PHONY : Kinect/DriveKinect.s

# target to generate assembly for a file
Kinect/DriveKinect.cpp.s:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/Kinect/DriveKinect.cpp.s
.PHONY : Kinect/DriveKinect.cpp.s

Kinect/KinectBase.obj: Kinect/KinectBase.cpp.obj
.PHONY : Kinect/KinectBase.obj

# target to build an object file
Kinect/KinectBase.cpp.obj:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/Kinect/KinectBase.cpp.obj
.PHONY : Kinect/KinectBase.cpp.obj

Kinect/KinectBase.i: Kinect/KinectBase.cpp.i
.PHONY : Kinect/KinectBase.i

# target to preprocess a source file
Kinect/KinectBase.cpp.i:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/Kinect/KinectBase.cpp.i
.PHONY : Kinect/KinectBase.cpp.i

Kinect/KinectBase.s: Kinect/KinectBase.cpp.s
.PHONY : Kinect/KinectBase.s

# target to generate assembly for a file
Kinect/KinectBase.cpp.s:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/Kinect/KinectBase.cpp.s
.PHONY : Kinect/KinectBase.cpp.s

Kinect/TurretKinect.obj: Kinect/TurretKinect.cpp.obj
.PHONY : Kinect/TurretKinect.obj

# target to build an object file
Kinect/TurretKinect.cpp.obj:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/Kinect/TurretKinect.cpp.obj
.PHONY : Kinect/TurretKinect.cpp.obj

Kinect/TurretKinect.i: Kinect/TurretKinect.cpp.i
.PHONY : Kinect/TurretKinect.i

# target to preprocess a source file
Kinect/TurretKinect.cpp.i:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/Kinect/TurretKinect.cpp.i
.PHONY : Kinect/TurretKinect.cpp.i

Kinect/TurretKinect.s: Kinect/TurretKinect.cpp.s
.PHONY : Kinect/TurretKinect.s

# target to generate assembly for a file
Kinect/TurretKinect.cpp.s:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/Kinect/TurretKinect.cpp.s
.PHONY : Kinect/TurretKinect.cpp.s

LockSolenoid.obj: LockSolenoid.cpp.obj
.PHONY : LockSolenoid.obj

# target to build an object file
LockSolenoid.cpp.obj:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/LockSolenoid.cpp.obj
.PHONY : LockSolenoid.cpp.obj

LockSolenoid.i: LockSolenoid.cpp.i
.PHONY : LockSolenoid.i

# target to preprocess a source file
LockSolenoid.cpp.i:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/LockSolenoid.cpp.i
.PHONY : LockSolenoid.cpp.i

LockSolenoid.s: LockSolenoid.cpp.s
.PHONY : LockSolenoid.s

# target to generate assembly for a file
LockSolenoid.cpp.s:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/LockSolenoid.cpp.s
.PHONY : LockSolenoid.cpp.s

OperatorControl.obj: OperatorControl.cpp.obj
.PHONY : OperatorControl.obj

# target to build an object file
OperatorControl.cpp.obj:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/OperatorControl.cpp.obj
.PHONY : OperatorControl.cpp.obj

OperatorControl.i: OperatorControl.cpp.i
.PHONY : OperatorControl.i

# target to preprocess a source file
OperatorControl.cpp.i:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/OperatorControl.cpp.i
.PHONY : OperatorControl.cpp.i

OperatorControl.s: OperatorControl.cpp.s
.PHONY : OperatorControl.s

# target to generate assembly for a file
OperatorControl.cpp.s:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/OperatorControl.cpp.s
.PHONY : OperatorControl.cpp.s

OurRobot.obj: OurRobot.cpp.obj
.PHONY : OurRobot.obj

# target to build an object file
OurRobot.cpp.obj:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/OurRobot.cpp.obj
.PHONY : OurRobot.cpp.obj

OurRobot.i: OurRobot.cpp.i
.PHONY : OurRobot.i

# target to preprocess a source file
OurRobot.cpp.i:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/OurRobot.cpp.i
.PHONY : OurRobot.cpp.i

OurRobot.s: OurRobot.cpp.s
.PHONY : OurRobot.s

# target to generate assembly for a file
OurRobot.cpp.s:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/OurRobot.cpp.s
.PHONY : OurRobot.cpp.s

Settings.obj: Settings.cpp.obj
.PHONY : Settings.obj

# target to build an object file
Settings.cpp.obj:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/Settings.cpp.obj
.PHONY : Settings.cpp.obj

Settings.i: Settings.cpp.i
.PHONY : Settings.i

# target to preprocess a source file
Settings.cpp.i:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/Settings.cpp.i
.PHONY : Settings.cpp.i

Settings.s: Settings.cpp.s
.PHONY : Settings.s

# target to generate assembly for a file
Settings.cpp.s:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/Settings.cpp.s
.PHONY : Settings.cpp.s

ShooterController.obj: ShooterController.cpp.obj
.PHONY : ShooterController.obj

# target to build an object file
ShooterController.cpp.obj:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/ShooterController.cpp.obj
.PHONY : ShooterController.cpp.obj

ShooterController.i: ShooterController.cpp.i
.PHONY : ShooterController.i

# target to preprocess a source file
ShooterController.cpp.i:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/ShooterController.cpp.i
.PHONY : ShooterController.cpp.i

ShooterController.s: ShooterController.cpp.s
.PHONY : ShooterController.s

# target to generate assembly for a file
ShooterController.cpp.s:
	$(MAKE) -f CMakeFiles/FRC_UserProgram.out.dir/build.make CMakeFiles/FRC_UserProgram.out.dir/ShooterController.cpp.s
.PHONY : ShooterController.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... FRC_UserProgram.out"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SFMLNetwork"
	@echo "... SFMLSystem"
	@echo "... AutonomousModes/Autonomous.obj"
	@echo "... AutonomousModes/Autonomous.i"
	@echo "... AutonomousModes/Autonomous.s"
	@echo "... ButtonTracker.obj"
	@echo "... ButtonTracker.i"
	@echo "... ButtonTracker.s"
	@echo "... Disabled.obj"
	@echo "... Disabled.i"
	@echo "... Disabled.s"
	@echo "... DriverStationDisplay.obj"
	@echo "... DriverStationDisplay.i"
	@echo "... DriverStationDisplay.s"
	@echo "... Kinect/DriveKinect.obj"
	@echo "... Kinect/DriveKinect.i"
	@echo "... Kinect/DriveKinect.s"
	@echo "... Kinect/KinectBase.obj"
	@echo "... Kinect/KinectBase.i"
	@echo "... Kinect/KinectBase.s"
	@echo "... Kinect/TurretKinect.obj"
	@echo "... Kinect/TurretKinect.i"
	@echo "... Kinect/TurretKinect.s"
	@echo "... LockSolenoid.obj"
	@echo "... LockSolenoid.i"
	@echo "... LockSolenoid.s"
	@echo "... OperatorControl.obj"
	@echo "... OperatorControl.i"
	@echo "... OperatorControl.s"
	@echo "... OurRobot.obj"
	@echo "... OurRobot.i"
	@echo "... OurRobot.s"
	@echo "... Settings.obj"
	@echo "... Settings.i"
	@echo "... Settings.s"
	@echo "... ShooterController.obj"
	@echo "... ShooterController.i"
	@echo "... ShooterController.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

